name: freezed_test
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0-55.0.dev <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.5
  freezed: ^1.0.0
  lints: ^1.0.0
dependencies: 
  freezed_annotation: ^1.0.0 
  json_annotation: ^4.3.0
  json_serializable: ^6.0.1

